name: medicine_appp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2
  intl: ^0.19.0
  pinput: ^5.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Antipasto
      fonts:
        - asset: font/AntipastoPro-Light_trial.ttf

    - family: Robot
      fonts:
        - asset: font/Roboto-Medium.ttf